- hosts: all
  become: yes
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install docker
      apt:
        name: docker.io
        state: present

    - name: install awscli via pip
      pip:
        name: awscli
        state: present

