apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-sample
  template:
    metadata:
      labels:
        app: devops-sample
    spec:
      containers:
      - name: app
        image: 704444257628.dkr.ecr.ap-south-1.amazonaws.com/devops-sample-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-sample-lb
spec:
  type: LoadBalancer
  selector:
    app: devops-sample
  ports:
  - port: 80
    targetPort: 3000
